# Generated by Django 4.0.4 on 2022-06-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemlist', '0002_rename_desc_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.CharField(default=None, max_length=3000),
            preserve_default=False,
        ),
    ]
