# Generated by Django 4.0.4 on 2022-06-01 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemlist', '0003_item_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='link',
        ),
    ]
